### ISSUE TITLE
curl getting empty pages

### ISSUE THREAD

**Issue by winkler1** [whazzmaster/fitgem-client#10]
So I'm following the instructions on http://fitbitclient.com/guide/playing-with-the-fitgem-api. Great approach BTW.

Problem is, the curl doesn't get anything - no error, either.
$ curl https://gist.github.com/whazzmaster/5322902/raw/4439e2d577567d280856a2d77cef7b824a851cd1/test-fitgem.rb
~/fitgem-sandbox

**Comment by cbowns** [comment]
Adding `-L` to the `curl` command will make it follow 301s.
