### ISSUE TITLE
Upgrade to OAuth2

### ISSUE THREAD

**Issue by tobernguyen** [whazzmaster/fitgem-client#18]
Do you have any plan to update this gem to OAuth2? With OAuth2 we can get more statistic from Fitbit API. For now what I know is that we can get heart rate if we use OAuth2 instead of Oauth.

**Comment by whazzmaster** [comment]
There's an open issue on the [fitgem repo](https://github.com/whazzmaster/fitgem/issues/44) discussing OAuth2 support.
