### ISSUE TITLE
Add full support for subscriptions

### ISSUE THREAD

**Issue by whazzmaster** [whazzmaster/fitgem-client#2]
Right now support for managing/consuming subscriptions is very experimental and not all-the-way implemented.  We should update the application so that it more concretely display how subscriptions are managed and consumed.

**Comment by ciregbulem** [comment]
Hey there,

Wondering if there has been any progress made towards this issue? I've noticed the #create_subscription method in the documentation but am not sure if it is fully functional yet and if so how exactly to use it. Thanks!

**Comment by whazzmaster** [comment]
Great question- I hadn't looked at these issues is a _very_ long while. To my knowledge, `create_subscription` should work correctly now, so I'll close this issue. If, in using it, you find issues we can re-open a new one issue against a particular problem.
